spring:
  profiles: 
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: mircoservicecloud-config-ppl-dev
---
spring:
  profiles: test #测试环境
  application:
    name: mircoservicecloud-config-ppl-test
    
#一定保存为UTF-8格式